// 图标类型
const BAR_CHART = 1;
const BAR_CHART_DOWN = 'BAR_CHART_DOWN';

const COLUMN_CHART = 2;
const COLUMN_CHART_DOWN = 'COLUMN_CHART_DOWN';

const LINE_CHART = 3;
const LINE_CHART_DOWN = 'LINE_CHART_DOWN';

const RING_DIAGRAM = 5;
const RING_DIAGRAM_DOWN = 'RING_DIAGRAM_DOWN';

const BAR_STACKED_CHART = 6;
const BAR_STACKED_CHART_DOWN = 'BAR_STACKED_CHART_DOWN';

const COLUMN_STACKED_CHART = 7;
const COLUMN_STACKED_CHART_DOWN = 'COLUMN_STACKED_CHART_DOWN';

const BAR_MAX_WIDTH = 50;
const BAR_MIN_HEIGHT = 5;

// 条形图配置
const BAR_SERIES_ITEM_TYPE = 'bar';
const BAR_LABEL_POSITION = 'right';

// 柱状图配置
const COLUMN_SERIES_ITEM_TYPE = 'bar';
const COLUMN_LABEL_POSITION = 'top';

// 折线图配置
const LINE_SERIES_ITEM_TYPE = 'line';
const LINE_LABEL_POSITION = 'top';
const LINE_SYMBOL_SIZE = 7;

// 图标区域滚动
const DataZoomWidth = 25;

// 图标配置颜色
const ColorArray = [
  '#FB6271',
  '#F0AF44',
  '#5CB3D9',
  '#F96E51',
  '#55C2C5',
  '#5295D9',
  '#FD7A7A',
  '#FE9B6A',
  '#F4D93E',
  '#EC9AF9',
  '#ED5DBB',
  '#94D8B3',
  '#1BB691',
  '#5A99E5',
  '#C6AAFF',
  '#F99C86',
  '#EEAA3B',
  '#8980EC',
  '#ED7940',
  '#78C657',
];

export {
  BAR_CHART,
  BAR_CHART_DOWN,
  COLUMN_CHART,
  COLUMN_CHART_DOWN,
  LINE_CHART,
  LINE_CHART_DOWN,
  RING_DIAGRAM,
  RING_DIAGRAM_DOWN,
  BAR_STACKED_CHART,
  BAR_STACKED_CHART_DOWN,
  COLUMN_STACKED_CHART,
  COLUMN_STACKED_CHART_DOWN,
  BAR_SERIES_ITEM_TYPE,
  BAR_LABEL_POSITION,
  BAR_MAX_WIDTH,
  BAR_MIN_HEIGHT,
  COLUMN_SERIES_ITEM_TYPE,
  COLUMN_LABEL_POSITION,
  LINE_SERIES_ITEM_TYPE,
  LINE_LABEL_POSITION,
  LINE_SYMBOL_SIZE,
  DataZoomWidth,
  ColorArray,
};
